### ISSUE TITLE
TypeError: create_connection() got an unexpected keyword argument 'ping_interval'

### ISSUE THREAD

**Issue by legoly** [unicorn-data-analysis/unicorn-binance-websocket-api#13]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you using the module on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Hardware
- [ ] Raspberry Pi

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)

#### Python Version Requirement
- [X] I am using Python 3.5.3 or above

#### Exact Python Version?
```
Python 3.6.5
```

#### Pip Version?
```
pip 10.0.1 from /Users/michaelbrill/Documents/projects/Telethon/env/lib/python3.6/site-packages/pip-10.0.1-py3.6.egg/pip (python 3.6)
```

#### Description of your issue

```
Copied example_demo.py and unicorn_binance_websocket_api_process_streams.py.

In unicorn_binance_websocket_api_process_streams.py, I changed line 36
old: from unicorn_fy import UnicornFy
new: unicorn_fy.unicorn_fy import UnicornFy

Then I execute example_demo.py:


(env) Michaels-MacBook-Pro:Telethon michaelbrill$ python example_demo.py

========================================== Starting aggTrade ==========================================

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/michaelbrill/Documents/projects/Telethon/env/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 142, in _create_stream_thread
    loop.run_until_complete(binance_websocket_api_socket.start_socket())
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/Users/michaelbrill/Documents/projects/Telethon/env/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_socket.py", line 55, in start_socket
    self.channels, self.markets) as websocket:
  File "/Users/michaelbrill/Documents/projects/Telethon/env/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_connection.py", line 88, in __aenter__
    self.handler_binance_websocket_api_manager.version})
  File "/Users/michaelbrill/Documents/projects/Telethon/env/lib/python3.6/site-packages/websockets/client.py", line 385, in __init__
    factory, host, port, **kwds)
TypeError: create_connection() got an unexpected keyword argument 'ping_interval'


```

**Comment by bithon** [comment]
hi logoly!
the current pip version is 19, please upgrade pip with `python -m pip install --upgrade pip` and then upgrade also to the latest version of unicorn-binance-websocket-api with `python -m pip install unicorn-binance-websocket-api --upgrade'. 

You write:
old: from unicorn_fy import UnicornFy
new: unicorn_fy.unicorn_fy import UnicornFy

To use unicorn_fy this way, you still have to use `from` and did you install unicorn-fy with PIP too?

**Comment by mmm3bbb** [comment]
Whoops, was in wrong account when logging issue. 

OK, so the problem was a websockets version dependency (another module was installing 6.0 and I think unicorn requires 7.0). 

I installed 7.0 and everything seems to be fine now.

Thanks so much for the module. I look forward to a life without connection timeouts. ;-)

**Comment by bithon** [comment]
Exactly, this lib depends on websockets 7.0, maybe i should add this info to the project :)

Your welcome! Happy to hear that!
